#https://datacrystal.tcrf.net/wiki/Pok%C3%A9mon_Red_and_Blue/RAM_map
from enum import Enum
class MemoryAddresses(Enum):
    BATTLE_STATE = 0xD057

    #---------------------------------MAP---------------------------------
    CURRENT_MAP_NUMBER = 0xD35E
    CURRENT_PLAYER_POSITION_Y = 0xD361
    CURRENT_PLAYER_POSITION_X = 0xD362
    

    #---------------------------------PLAYER---------------------------------
    BADGES_IN_POSSESION = 0xD356 #Binary
    POKEMON_IN_PARTY = 0xD163

    ##MONEY
    MONEY_1 = 0xD347
    MONEY_2 = 0xD348
    MONEY_3 = 0xD349

    ##FIRTS_POKEMON
    PLAYER_FIRST_POKEMON_NAME = 0xD16B
    PLAYER_FIRST_POKEMON_ACTUAL_HP_1 = 0xD16C 
    PLAYER_FIRST_POKEMON_ACTUAL_HP_2 = 0xD16D 
    PLAYER_FIRST_POKEMON_TOTAL_HP_1 = 0xD18D
    PLAYER_FIRST_POKEMON_TOTAL_HP_2 = 0xD18D

    PLAYER_FIRST_POKEMON_LEVEL = 0xD18C

    ##SECOND_POKEMON
    PLAYER_SECOND_POKEMON_NAME = 0xD197
    PLAYER_SECOND_POKEMON_ACTUAL_HP_1 = 0xD198
    PLAYER_SECOND_POKEMON_ACTUAL_HP_2 = 0xD199
    PLAYER_SECOND_POKEMON_TOTAL_HP_1 = 0xD1B9
    PLAYER_SECOND_POKEMON_TOTAL_HP_2 = 0xD1BA

    PLAYER_SECOND_POKEMON_LEVEL = 0xD1B8

    ##THIRD_POKEMON
    PLAYER_THIRD_POKEMON_NAME = 0xD1C3
    PLAYER_THIRD_POKEMON_ACTUAL_HP_1 = 0xD1C4
    PLAYER_THIRD_POKEMON_ACTUAL_HP_2 = 0xD1C5
    PLAYER_THIRD_POKEMON_TOTAL_HP_1 = 0xD1E5
    PLAYER_THIRD_POKEMON_TOTAL_HP_2 = 0xD1E6

    PLAYER_THIRD_POKEMON_LEVEL = 0xD1E4

    ##FOURTH_POKEMON
    PLAYER_FOURTH_POKEMON_NAME = 0xD1EF
    PLAYER_FOURTH_POKEMON_ACTUAL_HP_1 = 0xD1F0
    PLAYER_FOURTH_POKEMON_ACTUAL_HP_2 = 0xD1F1
    PLAYER_FOURTH_POKEMON_TOTAL_HP_1 = 0xD211
    PLAYER_FOURTH_POKEMON_TOTAL_HP_2 = 0xD212

    PLAYER_FOURTH_POKEMON_LEVEL = 0xD210

    ##FIFTH_POKEMON
    PLAYER_FIFTH_POKEMON_NAME = 0xD21B
    PLAYER_FIFTH_POKEMON_ACTUAL_HP_1 = 0xD21C
    PLAYER_FIFTH_POKEMON_ACTUAL_HP_2 = 0xD21D
    PLAYER_FIFTH_POKEMON_TOTAL_HP_1 = 0xD23D
    PLAYER_FIFTH_POKEMON_TOTAL_HP_2 = 0xD23E

    PLAYER_FIFTH_POKEMON_LEVEL = 0xD23C

    ##SIXTH_POKEMON
    PLAYER_SIXTH_POKEMON_NAME = 0xD247
    PLAYER_SIXTH_POKEMON_ACTUAL_HP_1 = 0xD248
    PLAYER_SIXTH_POKEMON_ACTUAL_HP_2 = 0xD249
    PLAYER_SIXTH_POKEMON_TOTAL_HP_1 = 0xD269
    PLAYER_SIXTH_POKEMON_TOTAL_HP_2 = 0xD26A

    PLAYER_SIXTH_POKEMON_LEVEL = 0xD268

    #---------------------------------OPPONENT---------------------------------
    ##FIRST_POKEMON
    OPPONENT_FIRST_POKEMON_NAME = 0xD8A4
    OPPONENT_FIRST_POKEMON_ACTUAL_HP_1 = 0xD8A5 
    OPPONENT_FIRST_POKEMON_ACTUAL_HP_2 = 0xD8A6 
    OPPONENT_FIRST_POKEMON_TOTAL_HP_1 = 0xD8C6
    OPPONENT_FIRST_POKEMON_TOTAL_HP_2 = 0xD8C7

    OPPONENT_FIRST_POKEMON_LEVEL = 0xD8C5

    ##SECOND_POKEMON
    OPPONENT_SECOND_POKEMON_NAME = 0xD8D0
    OPPONENT_SECOND_POKEMON_ACTUAL_HP_1 = 0xD8D1
    OPPONENT_SECOND_POKEMON_ACTUAL_HP_2 = 0xD8D2
    OPPONENT_SECOND_POKEMON_TOTAL_HP_1 = 0xD8F2
    OPPONENT_SECOND_POKEMON_TOTAL_HP_2 = 0xD8F3

    OPPONENT_SECOND_POKEMON_LEVEL = 0xD8F1

    ##THIRD_POKEMON
    OPPONENT_THIRD_POKEMON_NAME = 0xD8FC
    OPPONENT_THIRD_POKEMON_ACTUAL_HP_1 = 0xD8FD
    OPPONENT_THIRD_POKEMON_ACTUAL_HP_2 = 0xD8FE
    OPPONENT_THIRD_POKEMON_TOTAL_HP_1 = 0xD91E
    OPPONENT_THIRD_POKEMON_TOTAL_HP_2 = 0xD91F

    OPPONENT_THIRD_POKEMON_LEVEL = 0xD91D

    ##FOURTH_POKEMON
    OPPONENT_FOURTH_POKEMON_NAME = 0xD928
    OPPONENT_FOURTH_POKEMON_ACTUAL_HP_1 = 0xD929
    OPPONENT_FOURTH_POKEMON_ACTUAL_HP_2 = 0xD92A
    OPPONENT_FOURTH_POKEMON_TOTAL_HP_1 = 0xD94A
    OPPONENT_FOURTH_POKEMON_TOTAL_HP_2 = 0xD94B

    OPPONENT_FOURTH_POKEMON_LEVEL = 0xD949

    ##FIFTH_POKEMON
    OPPONENT_FIFTH_POKEMON_NAME = 0xD954
    OPPONENT_FIFTH_POKEMON_ACTUAL_HP = 0xD955
    OPPONENT_FIFTH_POKEMON_ACTUAL_HP_2 = 0xD956
    OPPONENT_FIFTH_POKEMON_TOTAL_HP_1 = 0xD976
    OPPONENT_FIFTH_POKEMON_TOTAL_HP_2 = 0xD977

    OPPONENT_FIFTH_POKEMON_LEVEL = 0xD975

    ##SIXTH_POKEMON
    OPPONENT_SIXTH_POKEMON_NAME = 0xD980
    OPPONENT_SIXTH_POKEMON_ACTUAL_HP = 0xD981
    OPPONENT_SIXTH_POKEMON_ACTUAL_HP_2 = 0xD982
    OPPONENT_SIXTH_POKEMON_TOTAL_HP_1 = 0xD9A2
    OPPONENT_SIXTH_POKEMON_TOTAL_HP_2 = 0xD9A3

    OPPONENT_SIXTH_POKEMON_LEVEL = 0xD9A1

    #---------------------------------EVENTS---------------------------------
    EVENT_FLAGS_START = 0xD747
    EVENT_FLAGS_END = 0xD87E
    MUSEUM_TICKET = 0xD754